on: workflow_dispatch

jobs:
  app-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: start app in another repo
        uses: peter-evans/repository-despatch@v2
        with:
          token: ${{ sercrets.REPO_ACCESS_TOKEN }}
          repository: Scrice994/todoFrontend
          event-type: app-start
          client-payload: '{"github": ${{ toJson(gitHub) }}}'

      - name: npm-ci
        run: npm ci

      - name: app-start
        run: npm start
