on: push

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm-ci
        run: npm ci

      - name: frontend-tests
        run: npm test
  
  call-e2e:
    runs-on: ubuntu-latest
    permitions: {}
    steps:
      - name: call-e2e
        - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/Scrice994/TodoE2E/actions/workflows/pr.yml/dispatches" \
          -d '{"ref":"main"}'
      
    
