name: trigger frontend
on: workflow_dispatch
jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the front end in another repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Scrice994/todoFrontend
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'
